build:
    run_tests:
        image: eistec/cpp-ci:latest
        environment:
            - CLICOLOR_FORCE=1
        commands:
            - mkdir build
            - cd build
            - cmake ..
            - make
            - make test
compose:
    serviceregistry:
        image: eistec/arrowhead-service-registry

matrix:
    CXX:
        - clang++
        - g++
