build:
    run_tests:
        image: eistec/arrowhead-ci-build:latest
        environment:
            - CLICOLOR_FORCE=1
        commands:
            - export $$TOOLCHAIN
            - mkdir build
            - cd build
            - cmake
             -DARROWHEAD_USE_LIBCOAP=$$ARROWHEAD_USE_LIBCOAP
             -DARROWHEAD_USE_LIBCURL=$$ARROWHEAD_USE_LIBCURL
             -DARROWHEAD_USE_PUGIXML=$$ARROWHEAD_USE_PUGIXML
             -DARROWHEAD_USE_LOG4CPLUS=$$ARROWHEAD_USE_LOG4CPLUS
             -DARROWHEAD_USE_JSON=$$ARROWHEAD_USE_JSON
             ..
            - make
            - make test
compose:
    serviceregistry:
        image: eistec/arrowhead-service-registry

matrix:
    TOOLCHAIN:
        - CC=clang CXX=clang++
        - CC=gcc CXX=g++
    ARROWHEAD_USE_LIBCOAP:
        - ON
        - OFF
    ARROWHEAD_USE_LIBCURL:
        - ON
        - OFF
    ARROWHEAD_USE_PUGIXML:
        - ON
        - OFF
    ARROWHEAD_USE_LOG4CPLUS:
        - ON
        - OFF
    ARROWHEAD_USE_JSON:
        - ON
        - OFF
