build:
    run_tests:
        image: eistec/cpp-ci:latest
        commands:
            - mkdir build
            - cd build
            - cmake ..
            - make
            - make test
compose:
    serviceregistry:
        image: eistec/arrowhead-service-registry
